export {default as About} from './about';
export {default as Contact} from './contact';
export {default as Home} from './home';
export {default as NotFound} from './notfound';
export {default as Pictures} from './pictures';
export {default as Table} from './table';
export {default as TickTock} from './ticktock';
export {default as Search} from './search';
export {default as SearchTable} from './searchtable';
