export { page } from './page'
export { bookmarks } from './bookmarks'
export { map, getGeohash, setMapQuery }  from './map'
export { solr } from './solr'
export { tasks } from './tasks'
export { theme } from './theme'
